FROM maven:3.9-eclipse-temurin-17-alpine AS build
WORKDIR /build
COPY . .
RUN mvn -DskipTests -pl schedule -am clean package

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=build /build/schedule/target/*.jar /app/
RUN rm -f /app/*.original || true && mv /app/*.jar /app/app.jar

EXPOSE 8083
ENTRYPOINT ["java","-jar","/app/app.jar"]
